### ISSUE TITLE
Publicar pacote no npm

### ISSUE THREAD

**Issue by gab0gomes** [Sysvale/vuex-make-request-store#2]

**Comment by geidsonc** [comment]
O nome do pacote será `@sysvale/vuex-make-request-store`?

**Comment by gab0gomes** [comment]
Acredito que sim, alguma outra sugestão?

**Comment by geidsonc** [comment]
Nenhuma outra sugestão.

**Comment by geidsonc** [comment]
Nesse caso vou alterar o nome do pacote

**Comment by geidsonc** [comment]
Publicado!

https://www.npmjs.com/package/@sysvale/vuex-make-request-store
